from __future__ import annotations

from pathlib import Path


def main() -> None:
    project_dir = Path(__file__).resolve().parent
    artifact_dir = project_dir.parent / "dist"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    artifact_dir.joinpath("index.html").write_text(
        """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bub Pages Generated Artifact</title>
  </head>
  <body>
    <main>
      <h1>Bub Pages Generated Artifact</h1>
      <p>This page was generated by a build command and published as an artifact.</p>
    </main>
  </body>
</html>
""",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
